console.log("It takes the few seconds")
// new Promise((resolve, reject) => {
//   setTimeout(()=>{
//     let error = true;
//     // console.log("Hey this is async function")
//     // reject("Technical issues");
//     if (!error) {
//       resolve("It perfectly work")
//     } else {
//       reject(" It's a technical error")
//     }
//   },2000)
// }).then((e)=>{
//   console.log(e+" It worked completly")
// }).catch((e)=>{
//   console.log("somthing went wrong "+e)
// })